### ISSUE TITLE
/rentroom 5

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#100]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=140971

Rent a room for 5 days and when you walk up to the door you get a fuel message, giving you the option to chose between Petrol and Diesel. Chose whatever and your screen freezes. Only works with 5.

http://i.imgur.com/dFJ0JXh.jpg

**Comment by TommyB123** [comment]
Should be fixed in 2.5.
