### ISSUE TITLE
/give doesn't work with the 'Bottled Water' item

### ISSUE THREAD

**Issue by JayChris98** [TommyB123/redcountyrp-bugs#102]
The command /give water [ID] [Amount] doesn't work. When you use the command, nothing shows up in the chat and no 'Bottled Water item' is given to the other player.
Steps to reproduce: Possess water bought from a 24/7 or from a Health clinic and try to give it to another player.

**Comment by TommyB123** [comment]
There's no code at all for giving water in the /give command, so idk why it's even listed as an option. Removed it, lol.
