### ISSUE TITLE
You're one year older in /stats than you are in /age.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#104]
> You are one year older in /stats than in /age. (e.g: in /age I'm 16 and in /stats I'm 17)

Steps to reproduce: 
1./age (check age)
2./stats (you're one year older than in /age)

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=142006#p1674470

**Comment by wtfrazr** [comment]
/age's age display is the one that's bugged.

**Comment by TommyB123** [comment]
Fixed.
