### ISSUE TITLE
Camp BOB Motel room owned by server.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#105]
> Yeah this was probably due to an account being deleted. Reloading the house would fix it. 

Couldn't get an admin in game to reload it, posting here instead.

[https://i.gyazo.com/7198f85725dc3647cc2759f580f5e9a8.png](url)

**Comment by wtfrazr** [comment]
Sometimes it signs a colplete different charater name to your room.

**Comment by TommyB123** [comment]
This happens when people delete their accounts. I can't really do anything about it, but they should hopefully clear when the motel wipe is done every 24 hours.
