### ISSUE TITLE
Payphone system is fricked.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#106]
If you decide to call a hotline number such as the SANews one, it won't let anybody else to use the payphone after you hang up and will generate a double message, one in the normal chat and one on the phone. http://imgur.com/a/nNYp5

If you call a random number which doesn't exist on a payphone,  the server thinks you are still on the phone even after automatically hanging up which prevents you from using /phone, /payphone /call etc until you logout.  http://imgur.com/FZ7ykMw

If you call for example 911 and use /h to hang up mid talk, the server still sees that payphone as being in use which prevents other people from using it until the server is restarted.  http://imgur.com/AOlR2iQ

Calling the County Radio FM hotline through a payphone shows the real phone number of the player, SANews' script says they do not accept calls from payphones, yet The CR accepts them, if they are let to accept calls from payphones, make it to be like with Elite Trucking where the number of the payphone is used. Due to that, if a player has no phone(dropped or just not on him), the message will show as (PN:0) as the PN value is set to 0.

If you have no phone on yourself and try to call a number that is not on a hotline via the payphone, it tells you that you have no credits to make the phone call. (easy check is to drop your phone and call the number through the payphone if you are alone).  http://imgur.com/a/G3D2t

**Comment by DogNo** [comment]
Also if you call a mechanic through the payphone, you will have your real phone shown. This leads to the CR bug where if you have no phone and call 118 via the payphone, it will say "0" as your number.  http://imgur.com/a/DKtYA

**Comment by TommyB123** [comment]
Fixed.
