### ISSUE TITLE
There are currently no unowned properties for sale.

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#109]
When you finish a page of properties in ST's dialog, and it kicks you out of it because there aren't any next pages, instead of telling somewhat like: "You reached the end of the properties list.", it tells you "There are currently no unowned properties for sale.".
Which is not true, cause I just rammed through at least 25 pages on the test server.

**Comment by The-Kenth** [comment]
Issue no longer exists, checked it out earlier and it works just fine.
