### ISSUE TITLE
Walking while /afk after /specoff in assistance

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#111]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=142511
If you are /afk and accept an assistance, type /vspec and then /specoff, you will be able to walk around as an afk guy.

**Comment by TommyB123** [comment]
SO WHAT???

**Comment by iamlarss** [comment]
^

**Comment by DogNo** [comment]
So what? SO WHAT? You are NOT supposed to move while AFK, first it's moving while AFK, next thing is you see yourself hacking guns and killing people in Monty park.

**Comment by TommyB123** [comment]
aaand stupid.
