### ISSUE TITLE
/lp bugged

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#112]
You can hear people using /lp, even if they are far from you. Simply the distance is bugged and it is not working as /lr, for example.

**Comment by TommyB123** [comment]
err, are you sure?

**Comment by Hypo9** [comment]
Yes.

**Comment by Hypo9** [comment]
yeah

**Comment by TommyB123** [comment]
I would like evidence as I see nothing wrong in the code.

**Comment by TommyB123** [comment]
invalid
