### ISSUE TITLE
The Bodybag Bug.

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#113]
Describe the bug you encountered. Please provide specific details as much as possible.

While placing a corpse inside a bodybag, if you place the corpse in it twice, it will double bag the body. This normally wouldn't be an issue, but it bugs the bodybag out to the point where you can't even pick it up and the only way to remove it is from a server restart.

Script Version: 2.4.6

Steps to reproduce:

1. Find a corpse and placing it inside a bodybag.
2. Grab another bodybag and type the same thing you just did.
3. Pickup the bodybag and remove it. Then try it again and see what happens.

CONFIRMED - 28/03/2017.

**Comment by The-Kenth** [comment]
Confirmed. Moved.
