### ISSUE TITLE
Calling a weapon crate & getting desynced right after.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#114]
If you call a weapon crate and then get desynced and have to relog, you won't get the message of the drop off point for the crate & you can't call the number for another 32 hours.

**Comment by TommyB123** [comment]
this isnt a bug

**Comment by DogNo** [comment]
The weapon crate still spawns though so it's normal for you to not be able to call the number until the cooldown is up.

**Comment by TommyB123** [comment]
invalid
