### ISSUE TITLE
Server forgot that a 31st day exists in a month

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#115]
The script seems to have forgotten that a 31st day exists in a month.

For example, if you use any features that show the date (/time, /lastonline, /mdc, etc.) on March 31st, the script will show April 1st instead of the current date (March 31st).

This issue has been present since December 2016.

**Comment by TommyB123** [comment]
no longer an issue.

**Comment by reemyrobby** [comment]
Still an issue. It was August 30th when it said I was online on "September 1st".
