### ISSUE TITLE
New players can't join / get stuck after login screen

### ISSUE THREAD

**Issue by Bauer-RCRP** [TommyB123/redcountyrp-bugs#12]
http://i.cubeupload.com/Zwc0LA.png

http://i.cubeupload.com/FIDpPf.png

More info: https://redcountyrp.com/acp/tickets/2145

- Bauer

**Comment by Bauer-RCRP** [comment]
MissBlue seems to have this issue as well and can't log in. So it's not only for new players.

**Comment by TommyB123** [comment]
I believe this has been fixed.
