### ISSUE TITLE
How to get infinite fire extinguishers

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#124]
If you /equip a Fire Extinguisher as FD, and then make it run out of ammunition, and then /equip another one, and then use disarm via /equip, you'll spawn with one permanently.

**Comment by reemyrobby** [comment]
Upon further investigation, the main issue is that fire extinguishers are not deleting after running out of ammo.

https://i.imgur.com/IpnmaYy.png
https://i.imgur.com/WjvlIag.png

**Comment by The-Kenth** [comment]
Issue no longer happens, it has been fixed by preventing players from equipping another fire extinguisher.
