### ISSUE TITLE
SANews" in SAN Network messages

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#128]
**Describe the bug you encountered. Please provide specific details as much as possible.**

In many messages related to SAN Network, it still says "SANews" or "SANNews". I can't be sure how many occasions of this there are, but I can verify that it does say "SANews" when you call our number, or when you go /duty on/off as a member.

**Steps to reproduce:** /call 726, or /duty on/off when in SAN Network. There's a possibility it occurs in other places too.

**Additional Information:** This has been the case for a very long time, but I thought it didn't matter until I was recently informed it actually says "SANNEWS" when you call 726. If all instances of "SANews" and "SANNews" would be replaced with "SAN Network", that'd be great.

**Comment by Hypo9** [comment]
Access link: https://redcountyrp.com/forum/viewtopic.php?p=1704006#p1704006

It is just some texit editing.

**Comment by TommyB123** [comment]
Fixed.
