### ISSUE TITLE
Corpse spawns inside of you, when you get it from the trunk.

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#129]
**Describe the bug you encountered. Please provide specific details as much as possible.**

When you collect a corpse into your vehicles trunk[/corpse trunk]. And when you remove it[/trunk get corpse]. The corpse will spawn in you, or on you, I don't exactly know to to describe it. But it does not let you move. You get stuck inside of the the corpse.

**Steps to reproduce:** Place a corpse into your trunk and then get it out. 

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=144423

**Comment by The-Kenth** [comment]
confirmed. moved.
