### ISSUE TITLE
Motel features still scripted in East Pacific Apartments

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#131]
The area of East Pacific Apartments in Fort Carson, where a motel used to sit before the town makeover map, still have the motel check-in features. The motel label is still visible outside, as well as the availability of motel check-in commands (although it will not work as the motel rooms for this area have already been removed from the database)

https://i.imgur.com/iuqpJap.png

**Comment by TommyB123** [comment]
SHHH
