### ISSUE TITLE
SASP respawn after dying

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#132]
**Describe the bug you encountered. Please provide specific details as much as possible.**

Whenever a SASP member dies, he/she is teleported to the DPD in stead of the hospital (which was intentional and perfectly fine). The problem is that you spawn inside the exterior of the DPD, a place you can not get out of. This results in SASP members having to call for an admin every time we die.

**Steps to reproduce: Get in SASP and get killed.**

**Comment by TommyB123** [comment]
Fixed.
