### ISSUE TITLE
Elite Trucking visual sirens do not detach

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#134]
The issue seems to affect a set of Elite Trucking vehicles that had visual sirens added in the recent script update.

When you use "/siren" in an Elite Trucking Dozer, Patriot, Roadtrain, Sweeper, Towtruck, Utility, or Yosemite, the odd-looking sirens remained attached even after turning them off.

(In bug report - https://redcountyrp.com/forum/viewtopic.php?f=1019&t=144648)

Steps to reproduce:

1. Enter a Yosemite.
2. /siren, it will go out of the vehicle.
3. /siren again to detach it, it will not detach.

http://imgur.com/Ue1QfIl.png

**Comment by OutW0rld** [comment]
Nor they're set on their proper coordinates.

**Comment by TommyB123** [comment]
Fixed.

**Comment by TommyB123** [comment]
Actually, the disappearing thing is fixed. The coords that were given to me are still wrong. I need working cords and the corresponding modelid as well, or else they'll remain bugged because I'm not going to waste my time fixing them for you.

**Comment by The-Kenth** [comment]
Confirmed the issue, moved accordingly.
