### ISSUE TITLE
Line break in tag text messes up the graffiti creation dialog box

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#138]
When you insert a line break in a graffiti text, the selection flow of the graffiti creation dialog box will mess up when you select an option. Due to this, you will not be able to spawn the graffiti. For example, if you have a line break in the text and you want to edit the font, it will show the font size dialog instead of the font face dialog.

https://www.youtube.com/watch?v=4IZd8G2CfQg

**Comment by reemyrobby** [comment]
It seems that it will also mess with the /edittag dialog box, as well as the admin command that list all graffitis.

https://i.imgur.com/1otfWiu.png

**Comment by TommyB123** [comment]
Fixed.
