### ISSUE TITLE
Server thinks that a player who is not connected in-game is still online

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#143]
This must be the counterpart of the old '/lastonline' bug.

I have noticed that Michael Barnes has been getting kicked for inactivity every 15 minutes. Upon further checking, he has not been in-game for a while, but commands like '/helpers' and '/id' show that he is still in-game, with Level 0.

Additionally, an administrator tried to use '/stats 96' (Michael Barnes' ID in /id), but no message prints out, not even the usual "That player is not connected in-game".

`	Line 73: [09:07:03] [Auto Kick] Kicked Michael Barnes (Reason: Inactive)
	Line 589: [09:22:03] [Auto Kick] Kicked Michael Barnes (Reason: Inactive)
	Line 1233: [09:37:03] [Auto Kick] Kicked Michael Barnes (Reason: Inactive)`

https://i.imgur.com/7EGiNDk.png

**Comment by reemyrobby** [comment]
The real Michael Barnes came in-game, and '/helpers' and '/id Barnes' now show two Michael Barnes online.

https://i.imgur.com/UAJ1FDG.png

**Comment by TommyB123** [comment]
I'll have to debug this. Not sure why it's happening.

**Comment by TommyB123** [comment]
I believe this is no longer an issue.
