### ISSUE TITLE
/rw

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#144]
/rw all - Works good. Rolls them all down/up

/rw 1 - rolls the driver's window up and down as supposed.
/rw 2 - Bugged, rolls the driver's window and not the passenger front right as supposed.
/rw 3 - Bugged, rolls the driver's window and not the passenger back left as supposed.
/rw 4 - Bugged, rolls the driver's window and not the passenger back right as supposed.

**Comment by TommyB123** [comment]
Are you sure? It works fine for me. What car were you testing this in?

**Comment by wtfrazr** [comment]
In Premier it doesn't work for me.
And people said that Burrito and bunch of other cars doesn't support the numbers.

**Comment by wtfrazr** [comment]
Should be a suggestion since only /rw and /rw all made it into the final version.
