### ISSUE TITLE
/changedob bug

### ISSUE THREAD

**Issue by JayChris98** [TommyB123/redcountyrp-bugs#15]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=138469

If you change your date of birth to anything which will make you older than 46, it will keep show the wrong age of 46.

**Comment by reemyrobby** [comment]
#230

**Comment by Jeroen52** [comment]
Most likely a bug due to this: https://en.wikipedia.org/wiki/Unix_time

**Comment by wtfrazr** [comment]
Moved to the new tracker.
