### ISSUE TITLE
/vattachment object brightness

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#151]
However it isn't a bug, but when you edit an object it has normal lighting settings, but when you attach it and save, it gets really bright. This can be an enhancement to the system that items get white color by default on them and furthermore you can color them with the same system working for /clothing.

Plus the headlight objects are always on at a night set time so it would be kinda neat having a feature that colors the headlight objects white after turning off the lights, and deleted the color from the object after turning on the vehicle lights.

**Comment by The-Kenth** [comment]
Confirmed. Moved.
