### ISSUE TITLE
Missing Additional DPD Entry Points

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#153]
The following entry points still need to be added to Dillimore Police Department:

Back Entrance - Exterior Entry Point: (/enter - Needs to be restricted to SASP members only)
`619.1471,-591.8467,17.1895,181.6160 ; Back Entrance - Exterior Entry Point`

Back Entrance - Interior Entry Point: (/exit)
`-742.4764,-391.6528,1408.7966,271.5355 ; Back Entrance - Interior Entry Point`

Balcony - Exterior Entry Point: (/enter - Needs to be restricted to SASP members only)
`607.8034,-548.1448,20.7745,90.7717 ; Balcony - Exterior Entry Point`

Balcony - Interior Entry Point: (/exit)
`-784.8542,-354.3148,1428.3217,182.7048 ; Balcony - Interior Entry Point (Colonel's Office)`

**Comment by TommyB123** [comment]
Yeah I'm aware of these. They're actually added on the database but there's a limit of 125 interiors currently and it needs to be raised before they will load.
