### ISSUE TITLE
Two cop skins in the clothing stores.

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#159]
There are two cop skins on Page 15 of the /buyclothes > 'Buy a new skin' command.
![sa-mp-107](https://cloud.githubusercontent.com/assets/24966760/25893271/6d6700a4-3577-11e7-8358-9102b7e65b8c.png)

Needs an urgent fix to prevent abuse.

**Comment by TommyB123** [comment]
fixed lol
