### ISSUE TITLE
kevlar vests

### ISSUE THREAD

**Issue by kremp** [TommyB123/redcountyrp-bugs#163]
hey! 👍 

> be me
> get shot :( [below 100 armor, let's say 90hp]
> 90hp
> Kevlar vest has gone.
> After RP has concluded, go to trunk to get a new kevlar.
> You are already wearing kevlar.

also, there needs to be a way to get 100 armor when u have like 6 armor or whatever, there's no way to drop armor / remove armor which is kinda dumb as it means there's random kevlar vests with 4 armor points everywhere (GET THEM GONE)

also **remove the bus bot** 💯 😃 😎

**Comment by wtfrazr** [comment]
ew emojis here.
I don1t think the bot needs to be removed.

**Comment by The-Kenth** [comment]
Confirmed. Moved.
