### ISSUE TITLE
Some players cannot exit the Palomino Bank

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#166]
Not sure if it is a real bug or just connection issue, but we get 4-5 or more assists a day for people being stuck in Palomino Bank. They say /exit, spamming H key, and relogging doesn't work.
I tested it myself, seemed to work like a charm for me, so I assume it is a personal connection issue.

I need confirmation from someone.

**Comment by reemyrobby** [comment]
The interior entry coordinates changed itself for some reason. That only needs to be adjusted.

**Comment by TommyB123** [comment]
A change I made to exiting/entering interiors that don't use pickups cause this. The radius is a little smaller now and the original position of the bank teleport seems to be off center from the actual entrance. Easy fix.
