### ISSUE TITLE
XP Points.

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#175]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=145508&p=1718802#p1718802

Describe the bug you encountered. Please provide specific details as much as possible.

When you level up the weapon skill from level 9 to level 10, you recive a bonus of 50 XP points, after relog the xp points dissapears.

Steps to reproduce:Level up the wep skill from lv 9 to 10 then relog.

**Comment by DogNo** [comment]
https://github.com/TommyB123/redcountyrp-bugs/issues/91 confirmed here.

**Comment by TommyB123** [comment]
Duplicate of #91. Closed.
