### ISSUE TITLE
Engine dialog after -attempting- to enter a faction vehicle stays on screen

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#176]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=145568&p=1718813#p1718813

Describe the bug you encountered. Please provide specific details as much as possible.

The engine dialog appears when attempting to enter a faction vehicle and after you get ejected automatically due it being a faction vehicle you remain with the engine dialog on the screen.

Steps to reproduce: 
1. Step inside a faction vehicle (which faction you're not in)
2. You'll see the result as shown in the screens below.
REMINDER: I was not desynced at all as you can see on the clock in the right top corner of my screen in both screens.

**Comment by TommyB123** [comment]
Fixed.
