### ISSUE TITLE
Unfreezing a Downed Player

### ISSUE THREAD

**Issue by 3abdel7aii** [TommyB123/redcountyrp-bugs#177]
https://redcountyrp.com/forum/viewtopic.php?f=1563&t=145617

Hey there,

So recently I discovered a bug which puts the downed player out of the "downed" anim and unfreezes them. Simply /cuff and then /drag, and then /stopdrag and /uncuff >> Those will unfreeze the downed player.

Solution; would be to prevent downed players from being cuffed.

**Comment by TommyB123** [comment]
Fixed.
