### ISSUE TITLE
/bizzviewguns doesn't Work

### ISSUE THREAD

**Issue by 3abdel7aii** [TommyB123/redcountyrp-bugs#178]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=145645#p1719230

 Store any weapon inside a business and use /bizzviewguns.

EDIT: You also can't see the guns on the UCP ~JayChris

**Comment by JayChris98** [comment]
You also can't see the guns on the UCP.

**Comment by TommyB123** [comment]
I never actually coded /bizzviewguns for some reason. Pretty funny how this was never found out during testing. :thinking:

**Comment by wtfrazr** [comment]
Slacking testers, pfff.

**Comment by TommyB123** [comment]
Fixed.
