### ISSUE TITLE
/corpses sends you under BB farm if you teleport to a deleted corpse.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#18]
If you type /corpses and before teleporting to the chosen corpse the body gets despawned, be it either by another admin, burnt or put in a bodybag, it will show you "You have been teleported to the corpse of Server" - http://imgur.com/4hX7w1I It can be easily checked if you set a body on fire, use /corpses and wait until the body despawns, then teleport to it and get sent under the BB farm.

**Comment by DogNo** [comment]
Just happened to find another one related to this. If you teleport to a corpse in a trunk, it will send you under BB farm too.

**Comment by TommyB123** [comment]
Both issues fixed.
