### ISSUE TITLE
/swat skin bug

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#182]
Go inside a swat enforcer and do /swat, you don't get the skin as before. (You're supposed to get it).

**Comment by TommyB123** [comment]
This happens when you don't have a skin in slot 4, for whatever reason. I'll look into it.

**Comment by OutW0rld** [comment]
What I meant is that you are supposed to get the swat skin once you do /swat inside the trucks but you don't. Only if you /swat at the station.

**Comment by TommyB123** [comment]
yeah you can't change skins inside of vehicles dum dum

**Comment by TommyB123** [comment]
Changing skins in vehicles causes client issues, hence why it's disabled. This never actually worked, by the way. Closing this.
