### ISSUE TITLE
/selectflist has the objects in a weird order.

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#185]
So before the 2.5 it had the order of new objects coming on the end.
Now it is weird because it is either based on distance from object or I don't know.
Basically I stand in a position, do /selectflist 2 and 3 objects pop up. When I step closer to these, instead of staying the same, they mix up. Really annoying when chosing within the same object models, and when you have 30 objects around you in a 3 meter area and you can't /selectf each object individually.

What happened to the old way when objects came on the end of the list, stayed in the same order, doesn't matter where I type in /selectflist next to them?

**Comment by TommyB123** [comment]
The list of objects is now grabbed directly from the streamer plugin rather than scanning through the furniture data and grabbing the model that way, so that's why it's different now and doesn't always produce consistent results. Not really a bug, simply a side effect of optimization. :^)

**Comment by wtfrazr** [comment]
I don't like it. :(
