### ISSUE TITLE
Ending an assistance as a helper in spectate mode brings you to the spawn screen

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#186]
As a helper, when you end an assistance while in spectate mode, you will be brought to the spawn screen (skin/team selection screen in SAMP) which you cannot get out of.

I am not sure about administrators though.

**Comment by wtfrazr** [comment]
It didn't do it for me though.

**Comment by reemyrobby** [comment]
Line 5077: [18:21:16] Returning to class selection after next death

I THOUGHT THIS WAS A THING.

**Comment by wtfrazr** [comment]
You pressed F4.

**Comment by reemyrobby** [comment]
i didnt ask for your opinion
