### ISSUE TITLE
Unable to exit the spawn (skin/team selection) screen

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#187]
When you are in the spawn screen (where you have the three buttons to select a skin and the button to spawn; skin/team selection screen in SAMP), you will not be able to get out of it even if you spam click "Spawn". You will have to /q to escape the doom.

This can be a bothersome if you accidentally press F4 and die.

**Comment by TommyB123** [comment]
yeah idk why this happens tbh

**Comment by The-Kenth** [comment]
Issue rarely happens and it's mostly a SAMP bug.
