### ISSUE TITLE
/furnlabels doesn't show up

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#188]
/furnlabels turned on but the labels dosn't show up in the following cases:
- Snapped object
- Bought object
- Duplicated object
- Upon /placef.

**Comment by wtfrazr** [comment]
Also it would be nice to have a SendClientMessage(); telling us that you selected an object with /editfurn. Just like /selectf does.

**Comment by wtfrazr** [comment]
+ notable bug that they are still showing up after storing them back to inventory.

**Comment by wtfrazr** [comment]
+ also notable bug that the system is fircked, they randomly stay active after being turned off.

**Comment by TommyB123** [comment]
Furniture labels weren't designed to update with furniture items, so this isn't really a bug, more like missing features. I'll probably add them eventually.
