### ISSUE TITLE
Object coords don't save on outfit

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#189]
I have 2 outfits which use the same sunglasses, despite of having **two different saved coords for them**, only 1 works.

http://i.imgur.com/PwuQfDn.jpg
Detective outfit on the left. Patrol on the right. As you can see, the coords for the sunglasses for "Patrol" are not loading and it keeps them in the position for "Detective".

**Comment by wtfrazr** [comment]
If you use the same bought object on different sized skins of course they won't fit.

**Comment by OutW0rld** [comment]
They are saved properly for each skin with different outfits.

**Comment by TommyB123** [comment]
Fixed.
