### ISSUE TITLE
You lose health even if you aren't being hit on your screen.

### ISSUE THREAD

**Issue by iamlarss** [TommyB123/redcountyrp-bugs#19]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=138648
Like I posted on there, I'm pretty sure this is just the way it has to be, but if you can fix it somehow due to serverside health, just let me know.

**Comment by TommyB123** [comment]
This was a "problem" before I implemented the new health system. I used [`OnPlayerGiveDamage`](https://wiki.sa-mp.com/wiki/OnPlayerGiveDamage) to handle melee damage, which essentially goes by what the player dealing the damage sees and then applies the damage to whoever they hit. The reason why I used this for melee damage is simply for better hit registration, the only drawback being how the damage receiver sees the person punching them. Nothing I can do about that 👍
