### ISSUE TITLE
Furniture labels stay on when disabled.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#190]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=145952

> So with the recent update I was messing around with furniture labels in my 6 Dusty Lane house. I turned it on, messed with it, turned it off and this one label decided to say "no i dont wanna go away"

The furniture labels don't go away after you disable them using the command.

**Comment by TommyB123** [comment]
I attempted a fix on this but didn't write anything in public because labels have always been sort of finicky for me. Let me know if it's still happening.

**Comment by wtfrazr** [comment]
They stay on if you are furnishing a house, have it on and then abandon furnishing permissions. Alrthough it can be turned off if you regain the permissions for the same house.

**Comment by The-Kenth** [comment]
Has been fixed.
