### ISSUE TITLE
Faction vehicles f00ked

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#193]
County Radio vehicles are fucked, they don't spawn, frespawn doesn't fix, some other faction vehicles are also fucked, IE you can"t use /gunrack on some SP vehicles as it'd tell you it's not a fac veh, RCFD vehs also affected

**Comment by TommyB123** [comment]
I believe this has stopped happening, but I'm not positive.

**Comment by reemyrobby** [comment]
Issue is still occurring. Vehicle is not listed in '/fcars'.

https://i.imgur.com/ewG2vsF.png

**Comment by dexev** [comment]
Still happening.

**Comment by TommyB123** [comment]
not really a surprise considering the last update was in AUGUST

**Comment by The-Kenth** [comment]
No longer happens unless you consume shrooms/peyotes in faction vehicles.
