### ISSUE TITLE
SASC doesn't have the MDC

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#194]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=146626
> v 2.5.1 R1 - San Andreas State Courts can now access the MDC.

lies

> The State Court assigned MDC has either not been implemented yet or is bugged as it doesn't recognize us as a government faction. Using it states that you should be in a government deployed vehicle. The feature isn't on the UCP either.

MDC isn't added for SASC.

**Comment by TommyB123** [comment]
There was an additional step to granting access to the MDC that I overlooked. woops.

Fixed.

**Comment by reemyrobby** [comment]
Reopened; still borked.

**Comment by TommyB123** [comment]
Fixed for real this time. :^)
