### ISSUE TITLE
Issues with Weed Pots' Mapping

### ISSUE THREAD

**Issue by The-Kenth** [TommyB123/redcountyrp-bugs#197]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=145702

When a weed plant is ready to be harvested, the pot appears lower than it's original placement. The issue persists after harvesting, and is only fixed by /reloadmyfurniture.

I'm going to quote what devex wrote as I think it pretty much could be the reason

[quote="dexev"]Speculating here, can't currently test.

I believe this happens because the unfinished weed plants have a different object to the finished plants, and the finished product's object has a bigger base which gives the illusion that they've fallen through the table but really they're just a bit bigger than the original pot.

This is what you see when first planting
[img]http://files.prineside.com/gtasa_samp_model_id/white/2203_w.jpg[/img]

This is what you see afterwards
[img]http://files.prineside.com/gtasa_samp_model_id/white/2241_w.jpg[/img][/quote]

**Comment by dexev** [comment]
A way this can be combated is to add in an object to /buyf called "weed pot" which would spawn this object with the plant texture set as transparent by default - http://files.prineside.com/gtasa_samp_model_id/white/2241_w.jpg

Once the weed has finished growing, the transparent texture will be removed from the object.

//

Another way to do this is to change the object completely to this -
https://i.gyazo.com/121ff0016ca886784dad38545e2b85d3.png

**Comment by wtfrazr** [comment]
3.0
