### ISSUE TITLE
"SignText: Can't create font Ariel"

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#20]
When I exited the Dillimore Police Department interior, I have noticed the text "SignText: Can't create font Ariel" popping onto my chat box four times.

This text seems to appear around the Dillimore area. I am guessing it is because it is supposed to be spelled "Arial" and not "Ariel"?

http://i.imgur.com/lzKEBuH.png

**Comment by rosalinee** [comment]
> it is supposed to be spelled "Arial" and not "Ariel"?

TOOOOOOMMY

**Comment by TommyB123** [comment]
lol fixed
