### ISSUE TITLE
Changelog Typo

### ISSUE THREAD

**Issue by 3abdel7aii** [TommyB123/redcountyrp-bugs#201]
Hey there,

There's a small issue regarding a typo within the changelog. 

In the changelog it says /setObjectSteamDistance; however, it should be /setobjectstreamdist.

I think it should be updated so that players looking for the command through /changelog would be able to find it.

**Comment by wtfrazr** [comment]
"Fixed." - TommyB 2k17, when the 2.5.1 came out. :+1: :100: Nice.

**Comment by TommyB123** [comment]
not rly that important since it's written properly in the actual changelog :^)
fixed regardless
