### ISSUE TITLE
Clothing items being turned into drug package object.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#203]
/holster a shotgun while having a clothing object on, it will transform that object into a drug package object. 

In my instance, I had eye glasses on when I did /holster, it didn't make the glasses disappear instantly but the drug package object appeared. When I did /clothing, the eye glasses object was turned into "Unknown" and when the unknown object was taken off, the glasses vanished and were never to be seen again. When I put the "unknown" object on, it spawns the drug package object.

**Comment by TommyB123** [comment]
Does this happen with just the shotgun or other weapons?

**Comment by dexev** [comment]
Haven't tried, got an update to this though.

When you store a shotgun in your house, the weapon object will remain on your ped but you won't actually have the weapon - as it's in your house.

http://i.imgur.com/RQ42MFE.jpg

**Comment by dexev** [comment]
With the new update, when you resize a backpack - it returns to its original size which is very very very annoying.

**Comment by TommyB123** [comment]
Fixed the backpack, I believe. Refer to #212 for the storing issue.
