### ISSUE TITLE
/confirmname bug

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#204]
If you entered the ACCEPT/DENY dialog of someone, and someone else accepts the namechange before you, then when you press escape or the DENY button, the namechange will be displayed as denied in the chat but the name of the player won't be affected. So basically you can still deny a namechange, but it is like the player would have made another request.

**Comment by The-Kenth** [comment]
Issue has been fixed by giving the second helper a text saying "Name change has already been handled"
