### ISSUE TITLE
"4" in helper messages

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#205]
When an administrator or helper takes an assistance, some weird string is shown on the assist messages. The same goes when they accept or deny a name change request. End assistance is not affected, however.

"**4** [Assist Msg] Emily Bett is now assisting Ege Fahri(75) after waiting for 34 sec.
**4*** Helper Jack Clinton has confirmed Francis Heston's name change to Dog No.
**4*** Isaiah Crenshaw has denied Dog No's name change to  [Reason: no].

EDIT 1: There is also a blank space before the messages.
EDIT 2: Issue only affect helper messages, not admin messages.

**Comment by TommyB123** [comment]
Fixed.
