### ISSUE TITLE
Seeing house messages from another home.

### ISSUE THREAD

**Issue by CaveFM** [TommyB123/redcountyrp-bugs#206]
When inside a different house you can get messages from another player home if they unlock or lock the house from the inside. If they shout inside their house, you can also see the message while in your own house interior which are completely different virtual worlds.

For example;
If you're in 6 Greenhill you can see unlock and lock messages from 2 Rooly Way.
If they shout inside 2 Rooly, the player inside 6 Greenhill can see it too.

**Comment by TommyB123** [comment]
Fixed.
