### ISSUE TITLE
Cannot /tow vehicles on mapped surface

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#215]
If you are on a mapped surface and there is no default GTA object below it, you cannot tow the car.
Places like Blueberry Apartment and such mapped areas are fall under this bug.

**Comment by TommyB123** [comment]
I believe this is an issue with SA-MP.

**Comment by The-Kenth** [comment]
Tried to replicate the bug and I got nothing out of it. I believe that the issue no longer exists.
