### ISSUE TITLE
Dillimore Automotive Dealership Bug

### ISSUE THREAD

**Issue by Hypo9** [TommyB123/redcountyrp-bugs#217]
Describe the bug you encountered. Please provide specific details as much as possible.
Well, I recently tried to purchase a Fortune but I used the command /viewstock instead of /viewcars which allows me to see the cars. I pressed Fortune in /viewstock and then I pressed enter then I was shocked when it spawned a Nebula when I clicked on the Fortune. I tried to purchase a Fortune and saw that it displayed a Nebula right after I press on the Fortune on the /viewstock tab.

Dillimore Automotive Dealership & Mr Grants Bike Shed Dealership's vehicles are showing the previous one in the purchase menu. This appears upon using /viewstock.

**Comment by TommyB123** [comment]
Fixed.
