### ISSUE TITLE
/cancelra and /requestadmin

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#226]
If I do a /requestadmin in an assistance and then end up ending the assistance (because admins doesn't answer, smh), then I still have my request but I cannot cancel it. /cancelra doesn't work.

**Comment by wtfrazr** [comment]
Duplicate to #162 
The whole /requestadmin is fricked if the assistance is closed without the admin joining.

**Comment by The-Kenth** [comment]
Confirmed. Moved.
