### ISSUE TITLE
Two bugs regarding the phone system.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#23]
If you drop 3 phones on the ground, you can pick up two of the oldest ones at the same time which will cause the latest one you picked up to get destroyed. Also if you buy a few phones (5 in my case) and drop each of them before buying a new one, when you type logout you will spawn with the dropped phones. If you keep on /dropping them after each /logout, you will still keep spawning with the dropped phones.
http://imgur.com/lbLySSs
http://imgur.com/wHbF77o

**Comment by TommyB123** [comment]
I believe I fixed this.
