### ISSUE TITLE
Vehicle sometimes get damaged when you exit the DPD Garage

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#231]
When you exit the Dillimore Police Department Garage, there is a chance that your vehicle will suffer minor damages upon exit.

It should also be noted that, for some reason, the vehicle becomes invisible upon exiting, but though this can be resolved by driving away from the entry point.

**Comment by wtfrazr** [comment]
moved to the other tracker together with #232
