### ISSUE TITLE
Entering a garage in a vehicle sometimes damages the vehicle

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#232]
When you enter a house garage in a vehicle, there is a chance that your vehicle will suffer minor damages upon /enter.

**Comment by TommyB123** [comment]
please be more specific. a custom garage or one of the predetermined garages??

**Comment by reemyrobby** [comment]
When I reported the issue, it was for one of the predetermined garages. However, it seems to occur in a custom garage as well.

https://www.youtube.com/watch?v=uS3K7l-0GNQ
https://www.youtube.com/watch?v=Kpm--FuFiOk

**Comment by wtfrazr** [comment]
#231
