### ISSUE TITLE
Vehicle falls through the custom garage floor

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#233]
Maybe it is an issue for laggers like me, but I experienced that my vehicles have a 90% chance of falling through my custom garage interior, when I enter it. (Talking about parked vehicles, not the one I am driving.)

Also they fall through 100% when the interior is being reloaded with /reloadmyfurniture.

**Comment by TommyB123** [comment]
There's really nothing I can do about this.
