### ISSUE TITLE
Journey spawn point.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#238]
If you've been on a different character(1) and then /logout and switch to the character whose spawn point is a Journey(2), it will spawn you at 1's spawn point but in a different virtual world. You have to /logout again and choose the character, then you'll be successfully spawned inside the Journey.

Edit: If you're first logging in and choose the character which spawns at the journey, this will happen
http://i.imgur.com/JX6Eq0C.png

Clicking the spawn button spawns you correctly though.

**Comment by The-Kenth** [comment]
Confirmed. Moved.
