### ISSUE TITLE
/lr still shows the radio freq.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#239]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=149244

"Radio frequencies will no longer show in radio messages." That is mentioned in Adjustments/Changes of the new version. Well, using /r won't show radio freq., but /lr will.

http://i.imgur.com/pjCVGSD.png

**Comment by TommyB123** [comment]
Fixed.
