### ISSUE TITLE
License Plate Bug

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#24]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=138741
I have taken a few pictures when I was able to recreate the bug. The vehicle was not always getting respawned either which resulted in the server saying it should have plates off while in fact I had them on.
http://imgur.com/a/dDeMu

**Comment by The-Kenth** [comment]
Fixed. Feature works perfectly.
