### ISSUE TITLE
Stingers only work at low speed

### ISSUE THREAD

**Issue by beccaaa** [TommyB123/redcountyrp-bugs#241]
Place down a stinger, drive over the stinger at high speed (testing in an Infernus with and without NOS) and the stinger doesn't pop tyres. Drive over the stinger at a fairly low speed though, and they're popped.

**Comment by Jeroen52** [comment]
Could be a check that is executed not often enough.

**Comment by wtfrazr** [comment]
Old script that doesn't work with a higher tickrate.

**Comment by Jeroen52** [comment]
Exactly.

**Comment by TommyB123** [comment]
Fixed.
