### ISSUE TITLE
Repairing your car in a garage makes it disappear from /mycars

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#25]
Once you repair a vehicle in any garage, after collecting it from the garage you will notice that it no longer shows in /mycars. I have noticed it on the live server when a player makes an assistance to find his car but it's not shown on /mycars at all. 
Before:  http://imgur.com/HAbZc9K
After: http://imgur.com/D2JgdSM

**Comment by TommyB123** [comment]
Is this still happening?

**Comment by DogNo** [comment]
Yes, I just tested it.
When you put it in the garage and type /mycars it will say "Being worked on at the [town name] garage."
After using /collectvehicle it will disappear from /mycars.

**Comment by TommyB123** [comment]
Fixed.
