### ISSUE TITLE
MExican cop skin

### ISSUE THREAD

**Issue by Dellmanjones** [TommyB123/redcountyrp-bugs#251]
I'm guessing the skin itself is actually bugged tbh, everything's a bit of a wiggler, but i think the editvest bone for him is attached to his pelvis

**Comment by TommyB123** [comment]
There's no custom logic put in place for this exact skin, that'd be stupid. Probably a bug with the skin itself, can't really fix that without actually putting in logic for that skin alone.

**Comment by The-Kenth** [comment]
Issue can't be fixed. Looocked.
