### ISSUE TITLE
Wrong address displayed when guestfurnish is revoked.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#252]
Title explains it all, pictures below too. It always seems to revoke your furnish for the correct property but it says Rumbley Block 11.

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=149927

http://i.imgur.com/amfzKHM.png
http://i.imgur.com/w0CDqn0.png

**Comment by TommyB123** [comment]
fixed.
