### ISSUE TITLE
Convertible roof not spawning on a car.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#254]
`"Alright so I bought a convertible roof for the blade from /mods and then /buymods confirm, but unlikely nothing changed I reloged a couple of times, even /q but nothing seemed to change. I sold the vehicle to one of my friends so they try it but it didn't work either. To me it seems like a bug.."`

Confirmed.
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=148197

**Comment by The-Kenth** [comment]
Works. Locked.
