### ISSUE TITLE
FD Mapping Bugs

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#256]
`Every time you leave the lobby you get stuck in the stairs or if you leave the interior to go into the bays you go under the mapping of the Fire Department.
`

`Yeah it is, the stream distance is really BORKED up at Station 11 and everything falls through it. -Bantrado`

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=144630#p1706823

**Comment by wtfrazr** [comment]
It's not about stream distance, those objects just need to be CreateObjects not CreateDynamicObjects.

**Comment by The-Kenth** [comment]
Issue has been fixed in-game. Tested it out a couple of times and it seems to be working just fine.
