### ISSUE TITLE
Lose side jahb upon being fired from faction

### ISSUE THREAD

**Issue by Dellmanjones** [TommyB123/redcountyrp-bugs#259]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=150412

shits legit, every SINGLE TIME

**Comment by reemyrobby** [comment]
wat

**Comment by Dellmanjones** [comment]
hop on the dev server pal and fire me from sasp my SIDEJOB will go away everytime.

**Comment by reemyrobby** [comment]
That is because the script will eject you from the vehicle to change your clothes to Slot 1. It does look stupid to get ejected even though you are not wearing Clothes Slot 5, but this particular issue is not a bug.

**Comment by Dellmanjones** [comment]
ODD. very odd.

**Comment by TommyB123** [comment]
You're thinking of regular jobs, which did indeed get reset when getting removed from a faction. This has been fixed.
