### ISSUE TITLE
Using phone while swimming.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#26]
Right now when you are in water, you can't use your phone as the message "You may not use your mobile phone while in water." is shown. This can be easily avoided if you pre-type the /call or /sms [number] before pressing left shift and jumping out and pressing T + enter to send the command. I guess it can be fixed if this animation check gets added too when trying to use your phone. - Swim_jumpout
http://imgur.com/L5VYq1L.png 
No idea if this can be fixed but you can also go to a shore, call somebody and then enter the water. You will still talk on the phone and it doesn't get interrupted at all.

**Comment by TommyB123** [comment]
Fixed for 2.4.6.
