### ISSUE TITLE
/nametags

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#262]
`When I type /nametags, the command would work perfectly all until a few seconds later where the nametags would just reappear again. I do this in conjunction with pressing F7 too to get rid of the hub but it also happens when I still have my hud on.
`
Confirmed, they disappear for a split second before reappearing.

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=150470

**Comment by TommyB123** [comment]
Fixed.
