### ISSUE TITLE
Custom garage with low /svo.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#265]
If you enter a custom garage on a vehicle with a low, 350 in my case. Your interior will have gaping blue holds in it until you get closer, I can't think of the friggin word because its almost 9am and i havent slept but its BORKED and it doesnt ignore your svo upon entering an interior

**Comment by dexev** [comment]
same things after crashing in an interior, when you return only 350 objects are streamed to your client despite spawning back in the interior

**Comment by wtfrazr** [comment]
I think the relogging thing isn't possible to fix, unless there is a data saved that you are/were in an interior.
If that would exist, it would also fix the garage issue where you stuck inside non-custom garages if you spawn inside one.

**Comment by TommyB123** [comment]
oops. Due to changes in logic inside of the vehicle teleport function, the visible object limit was only being set for passengers. This has been fixed for 2.6.
