### ISSUE TITLE
Spawning in Journey duplicates vehicle.

### ISSUE THREAD

**Issue by tyler12** [TommyB123/redcountyrp-bugs#270]
If you /changespawn 5 and re-log, the Journey is created but not assigned to /mycars meaning you can spawn another one with /vmenu.

**Comment by dexev** [comment]
this is already noted on the dev board and shouldn't be publicized here as it's a DUPE BUG dingus

**Comment by TommyB123** [comment]
I don't think this dude is a tester, but regardless I'll be fixing this bug soonish.
