### ISSUE TITLE
Vehicle Fuel Value Not Saving

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#274]
When a vehicle is respawned (relogging/garage collection/recovering), the vehicle's fuel would set to a certain value and does not load what it is supposed to be. This issue occurs in both personal and faction vehicles.

For example, if you have no fuel in your vehicle, you can simply relog and the vehicle will have fuel once again.

**Comment by TommyB123** [comment]
This should be fixed for 2.6.
