### ISSUE TITLE
Hanging up a phone still prints in the chat box.

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#276]
From what I know, all phone call messages should show in an annotated message.

When you attempt to call a number that will make it hang up immediately, the message would still show to everyone through the chat box.

Examples include: when you call a busy number, a hotline (County Radio/Elite Trucking/Mechanic Service/SAN Network), cancelling the emergency hotline through the dialog box, or by finishing the emergency hotline call.

> [16:35:23] Operator: "That number is either invalid or busy."
> [16:35:23] [Cellphone] {87CEFF}You hung up.
> [16:35:23] * Faye Delgado puts their phone away. *

> [16:39:06] Taxi Operator: 'Thanks for calling, there are currently no employees available, sorry.'
> [16:39:06] [Cellphone] {87CEFF}You hung up.
> [16:39:06] * Faye Delgado puts their phone away. *

> [16:39:11] 'I'm sorry but our help desk is currently offline, try again later.'
> [16:39:11] [Cellphone] {87CEFF}You hung up.
> [16:39:11] * Faye Delgado puts their phone away. *

> [16:39:16] We're sorry, we currently do not have any employees available.
> [16:39:16] [Cellphone] {87CEFF}You hung up.
> [16:39:16] * Faye Delgado puts their phone away. *

> [16:42:11] 'You're through to Elite Trucking, our help desk is currently unavailable. Please call back later.'
> [16:42:11] [Cellphone] {87CEFF}You hung up.
> [16:42:11] * Faye Delgado puts their phone away. *

> [16:44:49] You have reached the San Andreas emergency switchboard. Do you require Police, Fire or EMS?
> [16:44:51] Faye Delgado says (cellphone): [New York accent] Fire
> [16:44:51] 911 Dispatch: What is going on at your location?
> [16:44:52] 911 Dispatcher: Okay, we will cancel our units. Thank you.
> [16:44:52] [Cellphone] {87CEFF}You hung up.
> [16:44:52] * Faye Delgado puts their phone away. *

> [16:49:42] 'You've reached the San Andreas Mechanic Service, how may we assist you today?
> [16:49:44] Faye Delgado says (cellphone): [New York accent] qqtqt
> [16:49:44] [Cellphone] {87CEFF}You hung up.
> [16:49:44] * Faye Delgado puts their phone away. *

In case it is still confusing: The way it works now is that when you call a personal number and you (or the other line) hang(s) up, it would not print the "puts their phone away" message in the chatbox. It will also not show the message to nearby players. However, all instances above makes it print to the chatbox, but all hang up messages are supposed to be an annotated message.

**Comment by TommyB123** [comment]
Fixed.
