### ISSUE TITLE
Stock delivery crate duplicating when used multiple times

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#277]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=151073

When an Elite Trucking member gets a crate during stock delivery (/getcrate), the command can be used multiple times, which will make the crate object get stuck on your person even after bringing the crate to the business' front door. 

The bug reporter actually wanted to hide the crate and thought that using the command will make the crate disappear. It should be made similar to the "/getpizza" command where the object is removed after using the command the second time.

**Comment by TommyB123** [comment]
Fixed.
