### ISSUE TITLE
/togpay

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#278]
/togpay works fine, until you get a second paycheck - if you do /togpay and then wait another hour, get another paycheck, the number will display as normal.

**Comment by wtfrazr** [comment]
I believe the core mechanic of the command is to tog the current existing payday textdraw.
It makes sense that the next paycheck's textdraw appears since it is a new number at another hour.

**Comment by dexev** [comment]
upon redoing the /togpay command after the new textdraw has popped up, it says that the payday number has been re-enabled, leading me to believe that this is in fact a bug

**Comment by TommyB123** [comment]
Fixed.
