### ISSUE TITLE
Still can't open SMS histories

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#281]
title

**Comment by dexev** [comment]
whats the issue with it? i managed to access my sms history fine the other day.

**Comment by wtfrazr** [comment]
I think having a button of text messages cause the issue, cause after a while the dialog cannot display it and simply just doesn't show up, like you would close your phone menus.

**Comment by TommyB123** [comment]
I'm fairly sure the issue is indeed too many message histories. The SMS history code is actually fairly messy,  so it'll probably take me a little while to gauge this issue.

**Comment by TommyB123** [comment]
I've done a small refactor of SMS history code and I think I found the cause of the issue. Should be fixed for 2.6.
