### ISSUE TITLE
SPOOK CAR

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#284]
https://i.gyazo.com/667c8751c331913a93068e1af8ca5aca.jpg

This car has been spawned in for a week, I decided to get in it and see if it was a faction vehicle but it wasn't, seen in the screenshot above.

I asked Llamas if he could find out who owns the car and it appears its a GHOST CAR? Nobody owned it. It was spawned in for around a week and appeared in different parts of the map, broken down.

I had Llamas tp the car into the ocean and it got rid of it. 
Possibly linked to this?
https://redcountyrp.com/forum/viewtopic.php?f=1563&t=149484#p1768800

**Comment by wtfrazr** [comment]
Also two red Faggios in the are have been spawned since the last GMX.

**Comment by TommyB123** [comment]
I'll hold off on investigating any of these weird vehicle bugs until 2.6 is released. Reason being is I did a huge internal refactor of vehicle code, which should hopefully fix some of these bugs.

**Comment by dexev** [comment]
If these issues aren't fixed in 2.6, refer to this topic below.

https://redcountyrp.com/forum/viewtopic.php?f=1019&t=149696

**Comment by The-Kenth** [comment]
No further issues has been reported after the release of 3.0.
