### ISSUE TITLE
Getting fired from a faction deletes your clothing items.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#285]
Not all the time, but a lot of the time. Had lots of complaints about it.

**Comment by reemyrobby** [comment]
This should only occur if they have faction-restricted clothing items on their inventory. Have you confirmed that it was not faction clothing that he lost?

**Comment by dexev** [comment]
Yep confirmed.

**Comment by TommyB123** [comment]
It seems I was accidentally setting all new clothing items as faction items for some reason. Fixed.
