### ISSUE TITLE
/requestadmin does not clear when player leaves the server

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#286]
"If you request an admin and the player who you are assisting leaves the server, The /requestadmin will not cancel and you will not be able to request an admin in your next assistance, /cancelra will not work either."

Steps to reproduce: 
1) Have Player 1 make an assistance.
2) Request an admin via /requestadmin.
3) Have Player 1 leave the server (/q)
4) Have Player 2 make an assistance.
5) You won't be able to /requestadmin neither /cancelra.

**Comment by reemyrobby** [comment]
"Encountered the same issue today. Was assisting player 1. They used /logout to try and fix the problem after I had already used /requestadmin. Then, I wasn't handling any assist, and suddenly Lars joined the /ac chat. I was confused. Appearently a known bug to some administrators, as Lars said "oh it's bugged, just /logout and it'll be fixed".

**Comment by The-Kenth** [comment]
Confirmed. Moved.
