### ISSUE TITLE
Dillimore map glitch

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#292]
http://i.imgur.com/nmZMRq3.jpg

**Comment by dexev** [comment]
I reported this a long time ago & reminded Earl about it last month, this was the reply.

> "Can't, I deleted the map by mistake  :bangin: 
> 
> Tommy would need to send it to me, and even then I wouldn't be able to do much about it as I can't import code exported via TStudio. And even if I was I wouldn't be able to do much about it because there's no way for me to move the ground so that it doesn't stick out, cause it'll stick out on the other end. :U Razr said he's gonna do something about it but idk how its going"

It's up to razr at this point, been a thing since last year.

**Comment by wtfrazr** [comment]
Yeah, it is on its way inside a map with other objects, This can be closed cause I will most probably forget about it. And let's not collide map and script bugs anyways.
