### ISSUE TITLE
Dillimore Block 4.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#293]
After exiting my flat (#2), I can't exit the entire block and require a TP out.

**Comment by dexev** [comment]
Getting to be a major issue, not just in Dillimore Block 4 either, it's happening more regularly in random places - lots of assists about this.

**Comment by The-Kenth** [comment]
Merged with another bug report.

**Comment by Jeroen52** [comment]
Moving this over.
