### ISSUE TITLE
Double Shout Messages, Part 2

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#294]
"Well, I was inside the PC town hall and some people were talking in /s outside but it kept double-posting. I don't know if this is a bug or just an error in the script but I thought I'd inform the testers. "

https://i.imgur.com/oiq5PRm.png

**Comment by TommyB123** [comment]
Yeah, there was a small logic error which caused these double messages to happen. I already fixed it for 2.6.
