### ISSUE TITLE
Spawning at 0,0,0 coordinates after motel wipe

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#3]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=137003

When you rent a motel room and log back in after the motel wipe, you will spawn at 0,0,0 coordinates instead of the newbie spawn (ensuring that you have the motel set as spawn before the wipe).

**Comment by TommyB123** [comment]
Fixed for 2.4.5 R1.
