### ISSUE TITLE
No mods to remove.

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#300]
When you remove your last modification you get the grey "No mods to remove." message printed out as well. I don't think it is necessary to have since the player saw in the dialog that he has the last mod to remove. It can be printed out only when he tries the command again.

**Comment by wtfrazr** [comment]
https://i.imgur.com/b6E7mGy.png

**Comment by TommyB123** [comment]
It would be more trouble than it's worth to fix this message.
