### ISSUE TITLE
Taxi fare upon disconnect

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#301]
When a player disconnects there is no fare paid for the taxi driver. That way any player can avoid paying for the taxi driver, they just tab out near the destination and close their game. Poor driver left with no money and the player gets away with it because there isn't a rule for it to prevent. (except logging from RP but it cannot be literally forced to this situation and noone blinks an eye over that small money the driver lost)

**Comment by The-Kenth** [comment]
Confirmed & moved.
