### ISSUE TITLE
Rename all SASP-related entries to SACSO

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#302]
All entries related to "SASP" and "San Andreas State Police" need to be replaced with "SACSO" and "San Andreas County Sheriff's Office", respectively.

This includes, but is not limited to the following:
- /backup syntax (The radio message is fine);
- Pickup text draw;
- Alias subrank from "SPDB" to "CIU"'

Mapping Entries:
- DPD Exterior Front Mapping Text;
- DPD Interior Mapping Text:

1. (Main Lobby) San Andreas State Police -> San Andreas County Sheriff's Office
2. (Main Lobby) "To protect with courage, to serve with compassion." -> "Dedicated to your safety, the desire to serve your community." (HOLD THIS FOR NOW, NEED TO CONFIRM)
3. (Reception Area) For Floor Plan; High Command Offices -> Executive Staff Offices
4. (Reception Area) For Floor Plan; Command Offices -> Command Staff Offices
5. (Reception Area) For Floor Plan; remove Emergency Services Unit.
6. (Reception Area) For Floor Plan; see below for new division names.
7. (Main Lobby & Office) SPDB, State Police Detective Bureau -> CIU - Criminal Intelligence Unit
8. (Main Lobby & Office) Colonel -> Sheriff
9. (Main Lobby & Office) Lieutenant Colonel -> Undersheriff
10. (Main Lobby & Office) Major (2) -> Assistant Sheriff
11. (Main Lobby & Office) Replace one of the "Captain" text -> "Major"
12. (Main Lobby & Office) ESU, Emergency Services Unit, Weapons Room -> SWAT, Special Weapons and Tactics
13. (Main Lobby & Office) Patrol Operations -> Patrol Services Unit
14. (Main Lobby & Office) K-9 Unit -> Canine Services Unit
15. (Main Lobby & Office) ESU, Emergency Services Unit, Medical Room -> Medical Room

(To Be Updated...)

**Comment by reemyrobby** [comment]
To be forwarded to Smally for web development;

- Rename /sasp on the web MDC to /sacso;
- Replace the SASP logo with SACSO's logo;
- Ranking brackets on the MDC Roster (not badge tracker) is fricked.

**Comment by TommyB123** [comment]
I've done all of the script changes and adjusted the exterior, but I'd rather Earl updated all of the text inside of the map instead of me doing it so if he ever has to update the map, I won't have to redo everything.

**Comment by reemyrobby** [comment]
Has been forwarded to Earl.

**Comment by leeg98** [comment]
/help faction
One line returns: PD commands:

**Comment by wtfrazr** [comment]
Done?

**Comment by TommyB123** [comment]
The map was updated, all gucci here.
