### ISSUE TITLE
Off duty taxi drivers can see taxi cancelled message

### ISSUE THREAD

**Issue by leeg98** [TommyB123/redcountyrp-bugs#308]
When you're off duty as a taxi driver, you can see when an on-duty taxi driver cancels a players' taxi request.

**Comment by leeg98** [comment]
Steps to reproduce: 
1. Get taxi job.
2. Have a player /call 444
3. Have two taxi drivers present, one on-duty, one off-duty.
4. On-duty taxi driver /clearcaller [id].
5. Off-duty taxi driver sees the taxi cancelled message.

**Comment by TommyB123** [comment]
fixed
