### ISSUE TITLE
Speedo stuck on screen after being killed in a vehicle

### ISSUE THREAD

**Issue by suncaman** [TommyB123/redcountyrp-bugs#310]
Title basically sums up everything.

Steps to reproduce:
1. Get killed in a vehicle
2. /accept death
3. You'd see the speedo stuck on your screen wheter you're still waiting to get released from hospital/already spawned.

**Comment by wtfrazr** [comment]
This worths a test if any other textdraws that appear in set scenarios would do the same.

**Comment by Bzth** [comment]
I found this too - also found that with the nos it's gets stuck on your screen and the textdraw cuts off (on my screen anyway)

**Comment by TommyB123** [comment]
If this is a 2.6 bug keep it in the development board.

**Comment by reemyrobby** [comment]
not rly

https://redcountyrp.com/forum/viewtopic.php?f=935&t=152347

**Comment by suncaman** [comment]
Every vehicle you get killed in wheter you have NOS turned on or not, the speedo will be stuck on your screen if you die inside it.

**Comment by TommyB123** [comment]
Fixed.
