### ISSUE TITLE
/lastdriver doesn't give a last driver

### ISSUE THREAD

**Issue by Bzth** [TommyB123/redcountyrp-bugs#312]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=152289
"The /lastdriver cmd being very very buggy. After taking a faction vehicle from the impound, sometimes it will say that there is NO driver to this vehicle yet. Or there would be a name of a person, who ain't in even in the faction whose the vehicle it is. The only names, which register on /lastdriver should be from the same faction."
------------------

Confirmed. When you take a vehicle from the repair garage, it often doesn't give a last driver and this was confirmed on the test server and previously in game.

**Comment by Jeroen52** [comment]
Testing if this works in 3.0 R3.

**Comment by Jeroen52** [comment]
Moving.
