### ISSUE TITLE
Rare textline bug when doing the ET job

### ISSUE THREAD

**Issue by suncaman** [TommyB123/redcountyrp-bugs#314]
Basically, once you start your ET job and get rid of the trailer by detaching it, then going into the second checkpoint of the job and then getting out of your truck, a message would pop up twice with "you must return to your truck within 15 minutes in order to complete the job" and then I get the same message after this one at the exact time but with 14 minutes instead. It happened to me only once and I couldn't reproduce it the second time but I think it does happen rarely thus the title.

How to reproduce the bug:
1. /truck while doing the ET trucking job
2. Detach your trailer after being close to the second checkpoint
3. Go into the second checkpoint without the trailer 
4. Try to get out of the truck and the double textline should pop up
![sa-mp-878](https://user-images.githubusercontent.com/32344557/31045636-de41467e-a5f0-11e7-9b50-b343858d3a59.png)

**Comment by The-Kenth** [comment]
Haven't been able to replicate. L&A'd
