### ISSUE TITLE
Government Faction Bikes/Boats/Planes Having MDC Access

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#316]
Government faction members are able to use the MDC on faction bikes (pushbikes and motorcycles), boats, and planes. I am not entirely sure about the last two, but using an MDC on a bike is an obvious no.

**Comment by wtfrazr** [comment]
Boats and planes have space for a laptop or whatever cops use, right? The bikes are indeed unrealistic.

**Comment by TommyB123** [comment]
Fixed.
