### ISSUE TITLE
Vehicle /repair bug

### ISSUE THREAD

**Issue by suncaman** [TommyB123/redcountyrp-bugs#318]
This bug https://redcountyrp.com/forum/viewtopic.php?f=1019&t=153179 (Facton Vehicle /repair bug)

Basically, while exiting a vehicle and you /repair at the same time, you'd still have the repair menu popped on your screen and if you try to repair your vehicle, a textline shows up with "Your  has been booked for a full repair costing $xxxx, come back in around x hour (( x x x )) to collect it.

**Comment by The-Kenth** [comment]
Moved.
