### ISSUE TITLE
/changedob won't let you be older than 47

### ISSUE THREAD

**Issue by Bzth** [TommyB123/redcountyrp-bugs#319]
"**Describe the bug you encountered. Please provide specific details as much as possible.**
So I wanted to set my age at 65 but when I wrote the date it was stuck at 47 years, I mean if it's under 47 years it takes the right value, but when it's over 47, it stucks there.

Technical Information
**Script Version:** 2.5.2

**Steps to Reproduce:** Do for example /changedob 25 4 1955 and then /changedob 25 4 1945 and you will see that it's stuck at 47 years."

**Comment by wtfrazr** [comment]
Duplicate to #15
