### ISSUE TITLE
Movable dances keep playing whilst downed

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#321]
When you use the movable dances (/dance 8-11), and you get downed, the animation will keep playing.

This is how I explained it, though I could be wrong.

"This is occurring because of the nature of the 'dances' that let you move using the player movement keys. The loop of these dances are forced by the game engine which is why it is impossible to stop certain animations through the script (RMB) and have to press 'F' to stop them."

**Comment by wtfrazr** [comment]
'Cause this is thriller, thriller night...

**Comment by reemyrobby** [comment]
YOU'RE SPAMMING MY EMAILS.

**Comment by wtfrazr** [comment]
Is it better now?

**Comment by wtfrazr** [comment]
Or now?

**Comment by TommyB123** [comment]
Won't be a problem in 2.6.
