### ISSUE TITLE
Vehicles saved in a garage won't spawn on relog

### ISSUE THREAD

**Issue by Gigabitzz** [TommyB123/redcountyrp-bugs#322]
The title is not really how it is.

When you have your vehicle saved in a garage and take it outside for two minutes, there is a high chance that your vehicle will not spawn where it is supposed to be upon spawning your vehicle after relogging. The vehicle goes to a virtual world (possibly the garage's virtual world).

Steps to reproduce:
1. Save your vehicle in a garage (large/custom from my testing);
2. Take it outside of the garage for two minutes (or more);
3. Relog by using /logout or reconnect within 10 minutes;
4. Spawn your vehicle using '/vmenu'.
5. The vehicle will not spawn where it despawned from the relog.

**Comment by The-Kenth** [comment]
I believe that this has been fixed.
