### ISSUE TITLE
House music not playing when entering a custom garage

### ISSUE THREAD

**Issue by reemyrobby** [TommyB123/redcountyrp-bugs#324]
This is not necessarily a bug, but an overlooked feature, hence why it is labelled as an enhancement.

When you enter a custom garage, players should be able to hear the house's audio stream. Logic will need to be applied to the script, if ever.

1. If you enter a house from the custom garage on foot, you should be able to hear the house audio stream;
2. If you enter a house from the custom garage whilst in a vehicle, the car's audio stream should be prioritized. The house's audio stream will only play after exiting the vehicle.

**Comment by TommyB123** [comment]
Fixed.
