### ISSUE TITLE
/refill spam bug

### ISSUE THREAD

**Issue by suncaman** [TommyB123/redcountyrp-bugs#326]
Basically, when you have your car's tank below 100 and you want to /refill at a gas station. After choosing the type of gas (Petrol/Diesel) you can spam /refill how many times you want and after finishing refuelling your car the red marker will permanently stay on your screen.
![sa-mp-073](https://user-images.githubusercontent.com/32344557/31584406-9c42f174-b1b6-11e7-99be-145582f85c79.png)

**Comment by TommyB123** [comment]
Fixed.
