### ISSUE TITLE
/lock on a trailer doesn't prevent entering the back interior

### ISSUE THREAD

**Issue by Sp4zzy** [TommyB123/redcountyrp-bugs#327]
i had an idea that's been foiled because /lock on a trailer belonging to your faction doesn't stop people from being able to /enter the back interior of said trailer.

**Comment by wtfrazr** [comment]
Uh... what?

**Comment by Sp4zzy** [comment]
there's an interior, at the back of trailers that you can /enter.  If the trailer is locked you can still /enter it.  That's a problem.

**Comment by TommyB123** [comment]
Fixed.
