### ISSUE TITLE
Vehicle fuel bug - Resets to a lower count whenever re-spawned

### ISSUE THREAD

**Issue by B1sh0p123** [TommyB123/redcountyrp-bugs#330]
If you fill your fuel tank fully and decided to /logout - Upon return and spawning the vehicle, the fuel count of it will be two or three bars lower. 

Tested it with a faction vehicle too, the same result. Fill fuel-tank of your faction vehicle and respawn it, the fuel count is a bar or two lower.

**Comment by B1sh0p123** [comment]
Actually, the losing fuel count is completely random. Sometimes it's two bars, sometimes three or even four.

**Comment by reemyrobby** [comment]
‎Already fixed you cuk.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.

**Comment by B1sh0p123** [comment]
Oh!
