### ISSUE TITLE
/buyweaponskill doesn't work at Blueberry ammunation

### ISSUE THREAD

**Issue by suncaman** [TommyB123/redcountyrp-bugs#332]
What the title says.
![sa-mp-220](https://user-images.githubusercontent.com/32344557/32294432-db45a722-bf4e-11e7-9602-38ddf880253a.png)

**Comment by wtfrazr** [comment]
https://i.imgur.com/PW9JecZ.png
DUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUDE.

https://redcountyrp.com/forum/viewtopic.php?f=571&t=154215

**Comment by dexev** [comment]
OJB\EAGVOBWE G
