### ISSUE TITLE
Fuel issues

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#334]
Not really sure about it, but sometimes the car's fuel tank gets refilled or drained down by itself.
It happened both with my newly bought Sanchez and a second hand Sabre. I was just riding around without refuelling, noticed that my fuel is low, I wanted to pull up on a fuel station but I forgot. Next day the tank was full. Magic. Might have a connection with a player freshly purchasing a vehicle, either from DS or from a player.
Also saw someone in assistances that their fuel tank drained by itself. That might just be a stolen vehicle respawned upon login but not really sure.

If it happens it is a very rare bug, so it needs testing.

**Comment by B1sh0p123** [comment]
Already fixed for 2.6. Bug ID #274
