### ISSUE TITLE
Spawn point changes for no reason

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#335]
When you sell a house or buy a house from someone, your spawn point changes for no reason.
I sold my house that I no longer spawn at (ergo the spawn option isn't assigned to it) and my /changespawn changed to the noob spawn. Shouldn't really change when you are not getting rid of the house you actually spawn at.
Also when helping someone move houses, ergo buying it from them then selling it to their alt/main account then your saved house spawn changes again. Just why...

**Comment by dexev** [comment]
Fixed for 2.6
