### ISSUE TITLE
250 ammo in an AK

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#337]
You can get 250 ammo in an AK by simply using an ammo box.

**Comment by TommyB123** [comment]
??

![??](https://i.imgur.com/4hcj72A.png)

**Comment by dexev** [comment]
Shoot a bullet out of it and use the ammo box.

+ I found this.

I fell to my death, rezzed myself and my ammo doubled on my client but not serverside.
https://i.gyazo.com/81951ea44bdb183faa6a9a6ed4a09ae8.png

**Comment by The-Kenth** [comment]
Issue no longer exists, has been fixed. Tried to replicate it a couple of times and I still get 150 ammo.
