### ISSUE TITLE
Crumbled CJs stuck in vehicles.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#338]
https://imgur.com/a/eoSGA
https://imgur.com/P0k1sVt
Had several assistances about it yday, why is CJ taking over???

**Comment by dexev** [comment]
THAT'S WHAT THAT IS?

my lord, yes I've had this happen a lot. It's an issue with the uhhhh vattachments script that very much needs removing.

**Comment by wtfrazr** [comment]
I thought that was my modloader.

**Comment by wtfrazr** [comment]
moved
