### ISSUE TITLE
Sidejob vehicles not respawning.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#339]
/respawnsidejobcars sometimes doesn't work with certain sidejob vehicles.

**Borked:**
Bus sidejob vehicles don't respawn.
Trucker sidejob vehicles don't respawn.
Garbage sidejob trucks don't respawn.

**Working:**
Pizza Moonbeams work fine.
Coal miner vehicles work fine.

**Comment by The-Kenth** [comment]
Confirmed & Moved.
