### ISSUE TITLE
Furniture Duplication.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#34]
On some occasions, when you select the duplicate option it doesn't duplicate the selected object, it says you have duplicated the furniture item but it doesn't create a new object or take anything from your bank.

A relog solves the issue temporarily until you encounter it again.

EDIT: I managed to figure out why this is happening, if you do /sfl 2 and duplicate an object without setting your /payfurn preferance, you will encounter this bug.

**Comment by dexev** [comment]
Still having this issue.

**Comment by TommyB123** [comment]
not a bug dexev is just dumb (^:

**Comment by dexev** [comment]
frig off you're dumb for not doing stuff right go away
