### ISSUE TITLE
CMD:describe first checks if the target has a description instead of the distance between the player and target.

### ISSUE THREAD

**Issue by Jeroen52** [TommyB123/redcountyrp-bugs#343]
Not really an important bug, but one that is easy to fix.

CMD:describe firstly checks if the target has a description.

CMD:describe then checks if the target is in range of the player.

I feel that it should be turned around, as you can currently easily check all players across the map if they have a description.

**Comment by dexev** [comment]
You can't check someone's /describe if you're not near them though?

> [13:02:08] You must be close to the player.

**Comment by Jeroen52** [comment]
Yeah, but this way you can check if they have a description when they're at the other side of the map.
