### ISSUE TITLE
Spawning at Motorhome

### ISSUE THREAD

**Issue by Bzth** [TommyB123/redcountyrp-bugs#348]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=156568
When buying a Journey and using /changespawn and selecting Motorhome, when you /logout you'll spawn in an empty void.

"Steps to Reproduce:
1. Get a Journey
2. /changespawn to motorhome
3. Get kicked or logout once
4. Enjoy the fall or abuse /logout to respawn."

https://i.imgur.com/SyhhWkX.png

**Comment by The-Kenth** [comment]
Confirmed. Moved.
