### ISSUE TITLE
/rw [1, 2, 3, 4, All] as the driver.

### ISSUE THREAD

**Issue by B1sh0p123** [TommyB123/redcountyrp-bugs#352]
Well, as the driver of the vehicle, they can only control their window and all the windows. The means of specifically rolling down other windows independently while being the driver of the vehicle was initially released on the changelog v2.5.

"/rollwindows now supports each window independently. Each passenger can now manipulate their own window while the driver/passenger can control all windows."

But, there are only two parameters by which the driver is able to roll down/up the windows, '/rw' and '/rw all'. The driver cannot control the other windows individually using '/rw 2', '/rw 3', '/rw 4'. 

Not entirely sure if it's a bug or if its how the system was designed to function.

**Comment by wtfrazr** [comment]
The system was designed not to have the [1,2,3,4] options in its final version. Indeed it was intended to have these options but as you can guess it was removed mid-development.
/rw all is working as a driver so that isn't a bug either.

**Comment by B1sh0p123** [comment]
We could take it as a suggestion then, I suppose.

**Comment by wtfrazr** [comment]
Make a suggestion on the dev board then.
