### ISSUE TITLE
There is no way to get on the bed in the Journey.

### ISSUE THREAD

**Issue by Jeroen52** [TommyB123/redcountyrp-bugs#353]
There is enough space to walk around up there, but you can't jump on it.

It really seems like it should be possible and that it was intended that way, but it doesn't work.

If it was not intended to go up there, you should add a teleport from the stairs up to the bed.

**Comment by wtfrazr** [comment]
PM about this to Earl, unfortunately has nothing to do with scripting bugs.

**Comment by Jeroen52** [comment]
Sent it to him.

**Comment by Jeroen52** [comment]
![chrome_2018-01-26_05-46-36](https://user-images.githubusercontent.com/2915526/35459589-178bd3c0-02e1-11e8-90aa-73ab286fc6fc.png)

**Comment by Jeroen52** [comment]
I'm assuming that this will be corrected, as it'd make the Journey even better for roadtrips.
