### ISSUE TITLE
/lock bug

### ISSUE THREAD

**Issue by Bzth** [TommyB123/redcountyrp-bugs#358]
Basically for some unknown reason, /lock next to the SAN FBI Rancher locks the HQ (even when I'm in Dillimore and obviously the HQ is in Montgomery).
https://i.imgur.com/CbyXRMY.png

**Comment by The-Kenth** [comment]
Tried to replicate the issue a couple of times and couldn't get anywhere with it. I believe that the bug has been fixed for the time being, if it happens again feel free to post another bug report!

**Comment by Jeroen52** [comment]
I stand with @The-Kenth, I tried to reproduce this bug as well but couldn't.

The only reason it'd be incorrect is if you're dropping packets.
