### ISSUE TITLE
Golden nametag stays after transfering away.

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#36]
After doing /toggold, with a donator level capable for that, if you transfer the level to another player and you are no longer having a donator rank on that character, the server forgots to toggle the golden name back to regular.
![screenshot_82](https://cloud.githubusercontent.com/assets/24966760/21789875/8384a006-d6d8-11e6-98f1-ddeb01ca7a79.png)

**Comment by TommyB123** [comment]
Fixed.
