### ISSUE TITLE
Retrieving weapons from houses

### ISSUE THREAD

**Issue by CodacHomeboy** [TommyB123/redcountyrp-bugs#367]
Under some circumstances which I do not know, players are not able to take weapons from their house. A player reported that when he does /houseget and selects his MP5, the automated /me pops up but he does not actually receive the weapon, and the item remains in the house inventory. When testing for myself, I could take the MP5 but the player could not.

**Comment by The-Kenth** [comment]
I tried replicating the issue through almost every means possible, came back with nothing. Locked, if the issue persists, ask him to post another bug report.
