### ISSUE TITLE
/enter glitch

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#38]
If you enter car rentals via this gate http://i.imgur.com/0IjAXOH.jpg
With a **Sanchez and with one passenger**, one of the occupants goes to this location instead of going to the actual interior. http://i.imgur.com/4blIfGU.png

Tested several bikes, only managed to reproduce the bug with a Sanchez.

Looks like the objects didn't render but once there, you can walk around and the objects will never load.
Tested on the main sv and managed to reproduce it several times with Copfan.

**Comment by dexev** [comment]
This also happens to the SAN News garage. It could be a thing with all garages but that will need testing.

**Comment by TommyB123** [comment]
I believe it's a game issue because if it was an issue with code it would happen to all vehicles.

**Comment by DogNo** [comment]
Just tested, works with every garage and if you are on top of the vehicle when the driver is entering the garage/building you will get teleported to ls airport. http://imgur.com/a/WN34k

**Comment by OutW0rld** [comment]
So. This happens with every /enter point, not just Car Rentals or San News garage. If you also enter a garage and someone is car surfing you, the surfer will be TP'ed to different bugged places, depending which garage you're entering.

**Comment by TommyB123** [comment]
I've checked to see if a player is surfing on a vehicle when it gets teleported. Seems to have fixed the bug, so neat.
