### ISSUE TITLE
911 calls time

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#41]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=139161

When you call 911 on the main server it goes to the MDC one hour delayed, older calls have negative values. (even though the guy who reported the bug managed to get negative values straight away - I tried different call types, even FD ones and wasn't able to recreate the negative values)

On the dev server, it's delayed 3 hours compared to the IG time.

**Comment by OutW0rld** [comment]
It also happens with APBS and charges.

**Comment by reemyrobby** [comment]
This issue is occuring because all times in-game other than the running in-game time

**Comment by TommyB123** [comment]
It's a problem with the math when applying a GMT offset in the timestamp to date function I use. I've fixed this for the next update.
