### ISSUE TITLE
Error message upon removing empty bodybag 

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#42]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=139165

Quoting from original bug report because it's pretty straight forward.

> Step 1: "/bodybag get" at a faction vehicle (SASP in my example)
Step 2: "/bodybag remove" at a faction vehicle (SASP in my example) WITHOUT putting a corpse in it.

Unknown Command message is displayed

**Comment by TommyB123** [comment]
Fixed.
