### ISSUE TITLE
911 calls bugged with ESU subrank 

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#43]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=139160

Pretty easy.

SP BUG.
Have a random faction subrank > Then set it to ESU > MDC > View 911 calls > You won't see FD calls> View the information on any 911 call > Go back to the 911 calls menu > Now you see FD calls.

https://i.gyazo.com/d7d2b548bd983887da3af0c00ac3421c.png no fd calls
https://i.gyazo.com/2e66ec3a96892d02a76cfe61c3f8b541.png view the info on any call
https://i.gyazo.com/d1a84499b8ab54d9a0e26548c2591685.png back to the previous menu, now with FD calls

**Comment by TommyB123** [comment]
I plan to remake the MDC in the future, so this will probably have to stick around for now. The current MDC code is hard to navigate so it would be an incredibly annoying task to fix this.
