### ISSUE TITLE
Own 4 vehicles.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#44]
Have somebody to sell you a vehicle and go to a dealership and type /viewstock. When you choose a car press enter once for the confirmation window to show up and then press F6 so you can start typing in the chat, enter /accept vehicle and then purchase the fourth vehicle through the dealership. Nothing urgent as the /vmenu disallows to have four vehicles spawned at once but is not an intended feature. 
http://imgur.com/yBbeDfX.png
http://imgur.com/rsgFx72.png

**Comment by TommyB123** [comment]
Fixed.
