### ISSUE TITLE
Ability to use numbers in /changemyname

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#46]
You can use numbers to change your name for example Robby_Wilkinson2 and etcetera.
http://imgur.com/5Awxsae.png

**Comment by dexev** [comment]
There's also an ability to use invalid characters like 'ñ'

**Comment by TommyB123** [comment]
Are you sure special characters can be used in /changemyname? I believe I fixed this a while ago, but I'll look into the number thing.

**Comment by TommyB123** [comment]
I've fixed the numbers problem. It looks like the special characters fix is still working as well, so I'll go ahead and close this.
