### ISSUE TITLE
Rental vehicles /lock

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#48]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=139283

Quoting

> Step 1: Go to the Montgomery Information Center, get into a rent-able vehicle and do /rentvehicle
> Step 2: /lock them
> Step 3: /returnvehicle

Remains locked and has to be unlocked by an admin.

**Comment by TommyB123** [comment]
I don't know how many times I've had to fix this, but I think I got it this time. :^)
