### ISSUE TITLE
Furniture disappearing.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#52]
Random furniture objects disappear at random times.

https://www.youtube.com/watch?v=vnMGE4nGc6E

https://redcountyrp.com/forum/viewtopic.php?f=935&t=139297

**Comment by TommyB123** [comment]
I've seen this happen myself. Will look into it, although it will probably require debugging on the main server to trace the problem.

**Comment by dexev** [comment]
Still an issue, having it happen very frequently now.

**Comment by The-Kenth** [comment]
Issue has been fixed since 3.0
