### ISSUE TITLE
Mysterious fence appearances. 

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#54]
Fences are appearing in houses, however it's rare that it happens. I'm not entirely sure if it's someone abusing SAMP physics by being in the same interior VW & floating on the fence towards someone else's interior and placing it, or if it's a random bug.

> A fence appeared in my house and it is not visible on /selectflist. It does not reload when I /reloadmyfurniture as well.

https://redcountyrp.com/forum/viewtopic.php?f=935&t=139325

**Comment by TommyB123** [comment]
Rare bug. Easier to just delete the object when it happens than it is to track down the bug. Won't fix for now.
