### ISSUE TITLE
[OUTSIDE]; [INSIDE] multiplies

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#55]
So it is weird but this feature multiplies the [OUTSIDE] and [INSIDE] tags before anything that can be made visible in the chat between interiors and exteriors.
Shouts, megaphones... as if I am correct.
Multiplies it in random amounts. I've seen 2's, 6's .. everything.
![screenshot_90](https://cloud.githubusercontent.com/assets/24966760/22000318/caaded32-dc3e-11e6-99ed-66eed2c5bccf.png)
![screenshot_91](https://cloud.githubusercontent.com/assets/24966760/22000317/caadc3f2-dc3e-11e6-8613-e4b646bf4fe8.png)
![screenshot_92](https://cloud.githubusercontent.com/assets/24966760/22000316/caad3edc-dc3e-11e6-9a30-85188fd85803.png)

**Comment by TommyB123** [comment]
I honestly have no idea why this is happening. It doesn't even make sense given how the code is written, but I'll try to get to the bottom of it somehow.

**Comment by TommyB123** [comment]
Seems to be fixed now.
