### ISSUE TITLE
DPD /exit crashes cruisers

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#56]
When you /exit DPD garage with a cruiser, the majority of the times that deals damage to the cruiser. 
The car spawns in the air and when the scenario loads the vehicle falls down and loses HP.

Something related to the spawning position, I assume?

**Comment by TommyB123** [comment]
The ground of the DPD is always streamed in for players regardless of where they are, so I don't think stuff loading in is really the problem. I'll try to reproduce the issue and maybe fix it though.

**Comment by TommyB123** [comment]
Fixed.
