### ISSUE TITLE
/truck old checkpoint for FD station

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#57]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=139431&p=1644172
 
For the trucking mission, _"Eastern Basin Docks > SACFD Station 49 | Medical Supplies"_, the second checkpoint is still at the location of the old FD station. Coordinates need to be set to the new HQ in PC.

http://i.imgur.com/lTMdJkT.jpg

**Comment by TommyB123** [comment]
Fixed.
