### ISSUE TITLE
/removedateban 

### ISSUE THREAD

**Issue by Bauer-RCRP** [TommyB123/redcountyrp-bugs#58]
There are no callbacks for the removal of datebans for "this account has no dateban" or something similar. Instead, you can keep spamming every name you want and still get the same message every time. Annoying if you accidentally make a spelling mistake in the name and you think you've unbanned the person.

http://puu.sh/tqBsq/2e2c455c42.jpg

**Comment by Bauer-RCRP** [comment]
Would also be handy to rename this to /dunban or change /tunban to /removetimeban for consistency. (been searching my ass off for the /tunban)

**Comment by TommyB123** [comment]
I'll just make /unban work on all types of bans.
