### ISSUE TITLE
Driving while dead bug.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#59]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=139366
http://imgur.com/L5jfsoy.png
It's self explanatory, I managed to do it on my first try but it's nothing urgent.

**Comment by Alphabyte59** [comment]
simple RemovePlayerFromVehicle(playerid); in your onplayerdowned/death w/e callback should fix this @TommyB123 
im sure u'd find out urself but i wanna feel like i helped

**Comment by DogNo** [comment]
or just check if a player is downed/executed, if so they can't collect the vehicle lol (ALSO WHY AM I NOT COLLABORATOR YET, I GUESS I GOTTA SPAM MORE)

**Comment by TommyB123** [comment]
Fixed.
