### ISSUE TITLE
/equip doesn't work for ESU

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#60]
/equip doesn't work at SP faction vehicles like it used to, I'm sure I remember being able to /equip FD stuff at a cruiser and so does Novitality, it doesn't work anymore

**Comment by DogNo** [comment]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=139164 adding the link here for easier review of the bug and faster L&A once it's fixed.

**Comment by TommyB123** [comment]
Fixed on the current build.
