### ISSUE TITLE
Fort Carson Courthouse.

### ISSUE THREAD

**Issue by dexev** [TommyB123/redcountyrp-bugs#62]
Fort Carson Courthouse has no floor, when you enter the building you fall into the void.

**Comment by TommyB123** [comment]
Fixed. All I had to do was reload the map. In the future, please report these issues directly to me instead of making a bug report. 99% of the time it simply requires a map reload.

**Comment by Jeroen52** [comment]
@TommyB123 But that'd defeat the purpose of a bug tracker.

**Comment by TommyB123** [comment]
In this case it's a side effect related to #52. A simple reload to bring the object back suffices. It's not like the map itself is bugged, but another bug caused an object to disappear from the map.
