### ISSUE TITLE
/changedob doesn't go past Age 47.

### ISSUE THREAD

**Issue by Yassin69** [TommyB123/redcountyrp-bugs#67]
When doing /changedob, your age doesn't go past 47. Everything younger than that works fine.

/findyear works fine.

-----

https://www.youtube.com/watch?v=5uJubmikwTg

**Comment by DogNo** [comment]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=138469 I believe this was reported here.

**Comment by TommyB123** [comment]
Duplicate. Refer to #15 in the future please.
