### ISSUE TITLE
Faction/FD vehicles repairing themselves.

### ISSUE THREAD

**Issue by iamlarss** [TommyB123/redcountyrp-bugs#7]
Report: https://redcountyrp.com/forum/viewtopic.php?f=1019&t=138237
If you turn on /siren and /elm, crash the ambulance, give it 2 minutes, and then do /elm and /siren, it repairs the body. Doesn't fix the actual health of the vehicle, but repairs the body.

**Comment by TommyB123** [comment]
I don't think I can actually fix this.
