### ISSUE TITLE
/cuff makes you move back if you are dead and try to jump.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#72]
If you are downed or executed and cuffed at the same time, upon pressing left shift or any other button which makes you fall backwards, you will get launched behind and the whole animation will get bugged. Check out the video for better description of the bug. https://www.youtube.com/watch?v=T-cjfNwav68

**Comment by TommyB123** [comment]
This is a SA-MP bug. I can't fix it.
