### ISSUE TITLE
/changeoil command not recognized.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#76]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=139932&p=1650564#p1650564
Quoting myself on this one:
- If your bonnet/hood is open then you will get the standard white samp message "SERVER: Unknown command.". But if it's closed then you get the colored in gray RCRP message "The hood/bonnet must be open.".

**Comment by TommyB123** [comment]
I'm unable to reproduce this. What vehicle did you use?

**Comment by TommyB123** [comment]
Fixed.
