### ISSUE TITLE
Overhearing distant megaphone message from 3 Las Collinas.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#78]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=139966
For some weird reason the megaphone shouts were sent to this house too. Right now the DEV server is offline so I can't check the other houses too and I only got Cave to use the megaphone once as we tried it on the live server.

**Comment by DogNo** [comment]
Me and Outworld checked all Las collinas houses, only 3 Las Collinas seems to have this issue.

**Comment by DogNo** [comment]
A guy was using /m at the northern side of the rolling dice casino and I could hear him from the town hall in FC.

**Comment by TommyB123** [comment]
Should be fixed in 2.5.
