### ISSUE TITLE
/watchlist view is bugged

### ISSUE THREAD

**Issue by Sp4zzy** [TommyB123/redcountyrp-bugs#80]
ye

**Comment by TommyB123** [comment]
VERY DESCRIPTIVE

**Comment by Sp4zzy** [comment]
DO THE DAM COMMAND, /watchlist view just returns blank

**Comment by iamlarss** [comment]
"The watchlist is currently empty." That's all you get from it.

**Comment by TommyB123** [comment]
Fixed.
