### ISSUE TITLE
Time issues

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#81]
wat
It's the 30th of January and time displays are bugged af, man.
![screenshot_144](https://cloud.githubusercontent.com/assets/24966760/22425524/c20c203c-e6fb-11e6-84cf-b555e655c881.png)
![screenshot_143](https://cloud.githubusercontent.com/assets/24966760/22425525/c20c846e-e6fb-11e6-8ac9-572da150ab46.png)

**Comment by TommyB123** [comment]
Should be fixed now.
