### ISSUE TITLE
Fuel issues

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#82]
This happened after entering the car... I am pretty sure I left it ~80% full when left the server.
The fuel bar was full red... never seen that before.
![sa-mp-607](https://cloud.githubusercontent.com/assets/24966760/22430318/311f617a-e70e-11e6-82ec-3d78b569975a.png)
![sa-mp-605](https://cloud.githubusercontent.com/assets/24966760/22430319/31205d0a-e70e-11e6-924c-7acf316aa739.png)
![sa-mp-606](https://cloud.githubusercontent.com/assets/24966760/22430317/311cb2d6-e70e-11e6-9e99-70aa7bd77815.png)

**Comment by TommyB123** [comment]
this is bogus
