### ISSUE TITLE
Impounded faction vehicles disappearing until a server restart.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#85]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=140170
If you impound a faction vehicle and the server crashes or gets restarted nobody will be able to spawn it after releasing it from the garage which leads to it disappearing from /fcars and finally coming back on the next server restart. The reason is also changed from the full one to the first letter. (I.E from Ivan to I)

**Comment by TommyB123** [comment]
Fixed.
