### ISSUE TITLE
Textdraw shows less money that people are getting charged for while refueling with diesel.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#88]
https://redcountyrp.com/forum/viewtopic.php?f=935&t=140251&p=165426
The textdraw shows 5 dollars but players are getting charged for 10 each 5 liters. It's up to Tommy to decide if the diesel should cost more or the textdraw should show 10 bucks instead of 5.

**Comment by TommyB123** [comment]
Fixed.
