### ISSUE TITLE
Checkpoint System for Refueling and Changing Oil isn't working

### ISSUE THREAD

**Issue by 3abdel7aii** [TommyB123/redcountyrp-bugs#89]
Hey there,

So basically whenever you try to refuel your vehicle, a checkpoint would appear near the gas-cap of the vehicle. However; if you go to that marker and attempt to refuel your vehicle or change your vehicle's oil, nothing happens as the marker does not acknowledge your presence for some reason.

I've tested this issue with a Savannah and a bullet and they both wouldn't work for some reason.

**Comment by wtfrazr** [comment]
Can we just get back the old sys?
That worked, I don't know why it has been changed.
The new CPs are smaller, sometimes dislocated and you have to push the car to get them working.

**Comment by TommyB123** [comment]
Fixed in 2.5.
