### ISSUE TITLE
Shouting from outside

### ISSUE THREAD

**Issue by iamlarss** [TommyB123/redcountyrp-bugs#9]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=138294
Check his screenshot, [Outside] prints 4 times before the shout.

**Comment by reemyrobby** [comment]
I would like to add that if you are shouting from inside a business, the text "SERVER: Unknown command." shows up when doing so.

> [06:35:00] Robby Wilkinson shouts: .
> [06:35:00] SERVER: Unknown command.

**Comment by TommyB123** [comment]
@reemyrobby I noticed the issue in the code which caused that, it has been fixed.

I'm not really sure what's causing [OUTSIDE] to spam a bunch but I'll get to the bottom of it somehow.

**Comment by TommyB123** [comment]
huh forgot to close this when fix (^:
