### ISSUE TITLE
/payphone is fucked

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#93]
Mt Chillad payphone still doesn't work, /h doesn't clear payphones meaning once a payphone has been used after a server restart, it can't be used anymore

**Comment by DogNo** [comment]
By the way, MT Chiliad is a no signal area so why do we have a payphone there anyway?

**Comment by Jeroen52** [comment]
I'm assuming that payphone is a landline, and is thus not bound to signal strength.

**Comment by TommyB123** [comment]
Mt Chilliad's payphone isn't scripted I believe. I'll double check hanging up payphones though.

**Comment by wtfrazr** [comment]
Doesn't matter if it works or not, you just go inside the interiors there and you have signal anyways.

**Comment by OutW0rld** [comment]
Yeah, this needs fixxx. It happens with all payphones. You can only use it once, then it wont work again until the server is restarted.

**Comment by TommyB123** [comment]
Fixed.
