### ISSUE TITLE
Ending the pizza delivery brings up refueling dialog

### ISSUE THREAD

**Issue by Alphabyte59** [TommyB123/redcountyrp-bugs#96]

**Comment by Alphabyte59** [comment]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=140946&p=1662296#p1662296

**Comment by CaveFM** [comment]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=140971

Happens with multiple checkpoints. Seems to be random, I can't replicate it.

**Comment by TommyB123** [comment]
Fixed in 2.5.
