### ISSUE TITLE
Unable to cancel a shout-out (/call 442)

### ISSUE THREAD

**Issue by OutW0rld** [TommyB123/redcountyrp-bugs#97]
https://redcountyrp.com/forum/viewtopic.php?f=1019&t=141083

Pretty much that. Once the dialog shows up, if you hit cancel or esc that won't close the menu.

**Comment by TommyB123** [comment]
that's kinda intentional

**Comment by OutW0rld** [comment]
You w0t. /call 442 > Request the thing > Dialog shows up with two options > One of them is CANCEL, but it you choose that, nothing happens.

**Comment by TommyB123** [comment]
meh fixed
