### ISSUE TITLE
Whispering through closed window

### ISSUE THREAD

**Issue by wtfrazr** [TommyB123/redcountyrp-bugs#98]
So when the /rw is up, you can still whisper through.
Silly.
![screenshot_176](https://cloud.githubusercontent.com/assets/24966760/23177276/7f59b912-f866-11e6-81b4-be256a163500.png)

**Comment by wtfrazr** [comment]
Also the radio messages are visible through closed windows.

**Comment by CaveFM** [comment]
Not really a bug, just an inconvenience.

The radio is however bugged, people can still see it from a distance even though when the windows are up you can't hear what people are saying from the inside. Applies with both /r and /dr.

**Comment by TommyB123** [comment]
Fixed.
