### ISSUE TITLE
Online players that are not online.

### ISSUE THREAD

**Issue by DogNo** [TommyB123/redcountyrp-bugs#99]
Okay, the last time I have seen it, it was Rosalie here - http://imgur.com/Dx4az3Z.png
Today it was Marilyn Marsphire, she's online in /members but actually offline. The /lastonline shows a ridiculous amount of hours and /find gives the location of Fern Ridge if tracked. (north east south west etc is not given). I am unsure why it happens but it happens.

**Comment by DogNo** [comment]
Copfan5 just told me Tomato can't connect to the server because "he's already on".

**Comment by TommyB123** [comment]
Fixed.
